### ISSUE TITLE
[BUG] Does not let me even download

### ISSUE THREAD

**Issue by maxplayz2746** [danielbyomujuni/WorldSystem#238]
**Describe the bug**
cant download off of spigot

**To Reproduce**
Go to spigot resource page
hit the download button
nothing happens

**Expected behavior**
it dowloads

**Server Information (please complete the following information):**
- Server version: Paper version git-Paper-657 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- Installed plugins: BungeeGuard, CommandPanels, Essentials, PlaceholderAPI, ProtocolLib, SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion

**Comment by CrazyCloudCraft** [comment]
Umm latest updates are here: https://github.com/Argantiu/WorldSystem-Updated
